### ISSUE TITLE
Hot to map a property of a mapped object and sub objects

### ISSUE THREAD

**Issue by DrEight** [JohnMasen/ChakraCore.NET#11]
I'm trying to map an object but I've seen that are available only method and function.
Are the properties missing ? 
And, how can I map a sub object ?
For Example, how can I map the class A made only of properties ? 
class B
    {
        public string Name;
    }
    class A
    {
        public string Name { get; }
        public string Description { get; set; }

        public B Parent { get; }
    }

**Comment by JohnMasen** [comment]
for POCO class，suggest use structure object converter. JavaScript does not have property set,get method , so currently proxy converter supports methods and functions only.
The proxy converter can read/write properties from JavaScript object, but the value changes made inside the JavaScript code will not synced.
Actually node.js has same limitation, you can reference how node.js exports their system APIs.

**Comment by JohnMasen** [comment]
To help better understanding how to use this library, I will a demo project now, please check the read.me file on main page for more details.

**Comment by JohnMasen** [comment]
hi, I created a samples repository at https://github.com/JohnMasen/Chakracore.NET-Samples

hope this can answer your question

**Comment by DrEight** [comment]
Thank you, it works as expected
