### ISSUE TITLE
Attempting to terminate infinite loop

### ISSUE THREAD

**Issue by LeifRoss** [JohnMasen/ChakraCore.NET#13]
Great library! 
However I am struggling with this one issue.
How would you go about terminating a script that is stuck in a infinite loop?

I created a separate thread that attempts to terminate the script after 3 seconds, and to do so I have tried something like this:

```
        private async void Timeout()
        {
            try
            {
                await Task.Delay(3000, _cancel.Token);
                _timeout = true;

                if (_active && !_cancel.IsCancellationRequested)
                {
                    Console.WriteLine("attempting terminate");
                    _runtime.TerminateRuningScript();               
                    Console.WriteLine("terminated!");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message); // prints out "Runtime is active on another thread."
            }
        }
```

I have tried disposing both runtime and context, with and without thread interrupt. I can't directly abort the thread since that method was removed from .Net Core.

Runtime was created with the AllowScriptInterrrupt flag:
```
ChakraRuntime.Create(JavaScriptRuntimeAttributes.AllowScriptInterrupt)
```

**Comment by LeifRoss** [comment]
I have also tried wrapping everything in a separate thread, and then using a cancellation token to stop it, but to no avail.

**Comment by LeifRoss** [comment]
Found a slightly hacky way that seems to do the trick most of the time
```
Task<bool> t = _instance.CallFunctionAsync<JavaScriptValue, bool>("onParentChanged", _paramValue);
t.Wait(_cancel.Token);
result = t.Result;
```
instead of doing the await directly.

**Comment by JohnMasen** [comment]
There’s a JSRT method to “stop” the runtime.I can expose this in next version.

**Comment by LeifRoss** [comment]
That would be excellent, thank you!

**Comment by JohnMasen** [comment]
Hi LeifRoss:
I found this function is already implemented in `ChakraRuntime.TerminateRuningScript()` , please feel free to contact me if you find any questions.

**Comment by LeifRoss** [comment]
As shown in the snippet above, that function does not actually work, it simply freezes up the thread that is attempting to call it

**Comment by JohnMasen** [comment]
Ok, seems this a bug, I’ll have a look.

**Comment by JohnMasen** [comment]
Based on your description, seems the thread was blocked when the function is called. it is strange that the document says this API should not behavior like this.
Anyway I will create a test project to verify this. In the meaning time, could you please check if there's any thread sync conflict in your code?  Thanks.

**Comment by JohnMasen** [comment]
Bug confirmed, root cause found. will be fixed in next release.
A new method "ResumeScriptExecution" will be added.

**Comment by LeifRoss** [comment]
Excellent, thank you!

**Comment by JohnMasen** [comment]
code uploaded, a new project "PauseEngine" is added to source folder shows how to disable/enable runtime.
the nuget package will be updated in the next few days.

**Comment by LeifRoss** [comment]
Thank you, closing the issue!
